all : mini_operaciones
.PHONY : all

ejer5a : mini_operaciones.c
	@echo "Compilando..."
	gcc -Wall -o mini_operaciones mini_operaciones.c -lm
clean :
	@echo "Limpiando archivos..."
	$(RM) mini_operaciones 
