/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocolo.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
proy2dfs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Mensaje ls_1_arg;
		Mensaje getaddress_1_arg;
		Mensaje mkdir_1_arg;
		Mensaje cd_1_arg;
		Mensaje rm_1_arg;
		Mensaje cpy_1_arg;
		Mensaje mv_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case LS:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) ls_1_svc;
		break;

	case GETADDRESS:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) getaddress_1_svc;
		break;

	case MKDIR:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) mkdir_1_svc;
		break;

	case CD:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) cd_1_svc;
		break;

	case RM:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) rm_1_svc;
		break;

	case CPY:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) cpy_1_svc;
		break;

	case MV:
		_xdr_argument = (xdrproc_t) xdr_Mensaje;
		_xdr_result = (xdrproc_t) xdr_Mensaje;
		local = (char *(*)(char *, struct svc_req *)) mv_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PROY2DFS, PROY2DFSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PROY2DFS, PROY2DFSVERS, proy2dfs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PROY2DFS, PROY2DFSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PROY2DFS, PROY2DFSVERS, proy2dfs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PROY2DFS, PROY2DFSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
