/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocolo.h"

bool_t
xdr_Mensaje (XDR *xdrs, Mensaje *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Mensaje_val, (u_int *) &objp->Mensaje_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
