/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "functions.h"
#include <stdio.h>
#include <stdlib.h>

void
add_program_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	nums  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROGRAM, ADD_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Sum:\n");
	printf("First number \n");
	scanf("%i", &add_1_arg.a);
	printf("Second number \n");
	scanf("%i", &add_1_arg.b);
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Server returned: %i\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
minus_program_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	nums  minus_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MINUS_PROGRAM, MINUS_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Difference:\n");
	printf("First number \n");
	scanf("%i",&minus_1_arg.a);
	printf("Second number \n");
	scanf("%i",&minus_1_arg.b);
	result_1 = minus_1(&minus_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Server returned: %i\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int op;
	printf("Sum (0) or Difference (everything else)?\n");
	int ret = scanf("%i",&op);
	if (!ret) {
		printf("Error. Must enter a number.\n");
		exit(1);
	}
	if (op == 0)
		add_program_1 (host);
	else
		minus_program_1 (host);
exit (0);
}
