/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "functions.h"
#include <stdio.h>

int *
add_1_svc(nums *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Client asked for sum.\n");
	result = argp->a + argp->b;
	printf("Returning %i\n", result);

	return &result;
}

int *
minus_1_svc(nums *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Client asked for difference.\n");
	result = argp->a - argp->b;
	printf("Returning %i\n", result);

	return &result;
}
