/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <stdio.h>

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	int a = argp -> a,
		b = argp -> b;

	printf("Add function called on server with.\n");
	printf("a = %i\n", a);
	printf("b = %i\n", b);

	result = a + b;

	return &result;
}
