/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMA_ARREGLOS_H_RPCGEN
#define _SUMA_ARREGLOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct argumento {
	char arr[2048];
};
typedef struct argumento argumento;

#define SUMA_ARREGLOS_PROGRAM 0x20000000
#define SUMA_ARREGLOS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma_arreglos 1
extern  argumento * suma_arreglos_1(argumento *, CLIENT *);
extern  argumento * suma_arreglos_1_svc(argumento *, struct svc_req *);
extern int suma_arreglos_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma_arreglos 1
extern  argumento * suma_arreglos_1();
extern  argumento * suma_arreglos_1_svc();
extern int suma_arreglos_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_argumento (XDR *, argumento*);

#else /* K&R C */
extern bool_t xdr_argumento ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMA_ARREGLOS_H_RPCGEN */
